### ISSUE TITLE
Bug on submit after first error

### ISSUE THREAD

**Issue by rleija703** [yazonnile/svelidation#9]
**Problem:**
I have to click submit button twice on your quick code example.

I think it's because the field value validates on blur event and not on keypress. This so I have to get out of focus of the field and then press the submit button.

Also, the onSubmit event never triggered for me.

**Ideal solution:**
I don't have to get out of focus on a field.

Code:

```
<script>
  import createSvelidation from "svelidation";

  const { createForm, createEntry } = createSvelidation();

  // 2. create a validation model
  const [errorsStore, valueStore, useInput] = createEntry({
    type: "string",
    required: true
  });

  const onSubmit = ctx => console.log("on submit: ", ctx);

  const onSuccess = ctx => console.log("success:", ctx);

  const onFail = ctx => console.log("fail", ctx);
</script>

<form use:createForm={{ onSubmit, onSuccess, onFail }} on:submit|preventDefault>
  <input type="text" use:useInput bind:value={$valueStore} />

  {#if $errorsStore.includes('required')}
    This field is required
  {/if}

  <button type="submit">Submit</button>
</form>
```

**Comment by yazonnile** [comment]
Not sure what are you talking about
Just checked your example
Here os the result
https://user-images.githubusercontent.com/7853957/103045346-c0f5bc00-458c-11eb-8276-7e05a9a182df.mp4
If field is valid - you see submit event and success
If invalid - submit and fail

**Comment by yazonnile** [comment]
Feel free to reopen the issue or continue conversation if something is not clear
